---
title: "2022 House Polling & Women Voters"
output: html_document
date: "`r format(Sys.Date(), '%m/ %d/ %y')`" 
--- 
<br>

## **2022 House Elections Results. Republican gained 9 seats for majority with 50.6% to Democrats 47.8%. The gains for Republicans came from new seat created in Florida and shocking upsets in state of New York.**

<br>

```{r,out.width='100%', echo=FALSE} 
house_of_reps <- data.frame(
  party = c("Vacancies","Republicans", "Democrats", "Vacancies"),
  seats = c(0, 222, 213, 0  ),
  color = c("gray", "indianred2", "deepskyblue", "gray")
) 
house_of_reps <- house_of_reps %>% 
  mutate(party = as.character(party), color = as.character(color)) %>%
  parliament_data(election_data = .,
                            parl_rows = 8,
                            party_seats = .$seats,
                            type = 'semicircle')
ggplot(data = house_of_reps) +
  geom_parliament_seats(aes(x = x,  y = y, color = party)) +
  theme_ggparliament() +
  labs(title = "2022 U.S House Election Results")+
  theme(legend.position = "bottom")+
  scale_color_manual(values = house_of_reps$color, 
                     limits = house_of_reps$party)  
 knitr::opts_chunk$set(error = TRUE) 
```  

<br>

**Polling average of generic ballot and women voters for the 2022 midterms elections, polls used are at the bottom of the page**.

<br>



---------------------------------------------------------


```{r setup, include=FALSE}
library(dygraphs)
library(flexdashboard)  
library(readxl) 
library(ggplot2)
library(plotly)
library(knitr)
library(plyr)
library(scales) 
library(lubridate) 
library(magrittr)
library(tidyverse)
library(expm) 
library(dplyr)
library(DT) 
library(ggparliament) 
```

```{r, echo=FALSE}
genericbal<-read_excel(("~/Documents/RSTUDIO/kaejames.github.io/midterms22.xlsx"), sheet = "daily") 
knitr::opts_chunk$set(error = TRUE)
```

```{r, echo=FALSE}
monthly<-read_excel(("~/Documents/RSTUDIO/kaejames.github.io/midterms22.xlsx"), sheet = "month") 
knitr::opts_chunk$set(error = TRUE)
```

```{r, echo=FALSE}
tbpolls<-read_excel(("~/Documents/RSTUDIO/kaejames.github.io/midterms22.xlsx"), sheet = "table") 
knitr::opts_chunk$set(error = TRUE)
```

 
<br> 
 
```{r,out.width='100%', echo=FALSE}
p<-ggplot(genericbal)+
  geom_line(aes(x=Date, y=Ballot,colour=Party, group=Party), lwd=2) +
  labs(x="", y="", title = "Who is leading?",
       caption = "source;Echelon Insights, Fox News Poll & Monmouth University")+
  scale_color_manual(values =c("deepskyblue","indianred2")) +
  theme(plot.title = element_text(color = "black", family = "Ubuntu",  size = 17, face="bold", hjust = 0),
        plot.caption = element_text(color = "black", size=13, face = "italic", family = "Ubuntu"),
        legend.text = element_text(face = "bold"),axis.title.x = element_text(family = 'Ubuntu', face = 'bold'),
        axis.text.x = element_text(face = 'bold', angle = 0, hjust = 0.5),axis.text.y = element_text(face = "bold"),
        plot.subtitle = element_text(color = "black",family="Ubuntu", size = 13)) +
  scale_y_continuous(limits = c(35,55))
  
ggplotly(p, tooltip =c("Ballot", "Date"))  
``` 

```{r,out.width='100%', echo=FALSE}
p<-ggplot(genericbal)+
  geom_line(aes(x=Date, y=Women,colour=Party, group=Party), lwd=2) +
  labs(x="", y="", title = "Women - support for Congress",
       caption = "source;Echelon Insights, Fox News Poll & Monmouth University")+
  scale_color_manual(values =c("deepskyblue","indianred2")) +
  theme(plot.title = element_text(color = "black", family = "Ubuntu",  size = 17, face="bold", hjust = 0),
        plot.caption = element_text(color = "black", size=13, face = "italic", family = "Ubuntu"),
        legend.text = element_text(face = "bold"),axis.title.x = element_text(family = 'Ubuntu', face = 'bold'),
        axis.text.x = element_text(face = 'bold', angle = 0, hjust = 0.5),axis.text.y = element_text(face = "bold"),
        plot.subtitle = element_text(color = "black",family="Ubuntu", size = 13)) +
  scale_y_continuous(limits = c(35,60))
  
ggplotly(p, tooltip =c("Women", "Date"))  
``` 

<br>

## **All the polls used for the average**

<br>


```{r,out.width='100%', echo=FALSE}
datatable(tbpolls,extensions = 'Buttons',rownames = FALSE, options = list(
    dom = 'Bfrtip',
  buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),pageLength = 8
  )
) %>%
  formatStyle(
    'POLLSTER',
    fontWeight = 'bold'
    ) 
  
```
 

