---
title: "Battle For Westminister"
output: 
  html_document: 
    toc: true
    toc_float: true
    
    includes:
       in_header: tag.html 
date: "`r format(Sys.Date(), '%m/ %d/ %y')`" 

---

Great Britain[***England,Scotland and Wales***] opinion polling aggregation from public polls for the next general election which will likely be held in  ***winter of 2024 or January 2025***.

---------------------------------




```{r setup, include=FALSE}
library(dygraphs)
library(flexdashboard)  
library(readxl)
library(ggplot2)
library(plotly)
library(knitr)
library(plyr)
library(scales) 
library(lubridate) 
library(dplyr)
library(DT)
```

```{r, echo=FALSE}
ukpolls<-read_excel(("~/Documents/RSTUDIO/kaejames.github.io/GreatBritain.xlsx"), sheet = "chart", col_types = c("date", 
        "numeric", "text", "numeric")) 
knitr::opts_chunk$set(error = TRUE)
```

```{r, echo=FALSE}
tablepol<-read_excel(("~/Documents/RSTUDIO/kaejames.github.io/GreatBritain.xlsx"), sheet = "table") 
knitr::opts_chunk$set(error = TRUE)
```

## <span style="color: #4361ee;"> Polling Aggregate </span> 

```{r,out.width='100%', echo=FALSE}  
p<-ggplot(ukpolls,mapping=aes(x=Date, y=Aggregate,colour=Party, group=Party))+
  geom_line(lwd=1.5)+
  
  labs(x="", y="", title = "")+
  scale_color_manual(values =c("deepskyblue","green", "red", "orange","yellow")) +
  theme(plot.title = element_text(color = "black", family = "Ubuntu",  size = 17, face="bold", hjust = 0),
        plot.caption = element_text(color = "black", size=13, face = "italic", family = "Ubuntu"),
        legend.text = element_text(face = "bold"),axis.title.x = element_text(family = 'Ubuntu', face = 'bold'),
        axis.text.x = element_text(face = 'bold', angle = 0, hjust = 0.5),axis.text.y = element_text(face = "bold"),
        plot.subtitle = element_text(color = "black",family="Ubuntu", size = 13)) +
  scale_y_continuous(limits = c(0,55))
  
 ggplotly(p, tooltip =c("Aggregate", "Date"),source = "james")

```


<br>

### <span style="color: #4361ee;"> Seats Predictions </span>  

<br>


```{r,out.width='100%', echo=FALSE}
datatable(tablepol,extensions = 'Buttons',rownames = FALSE, options = list(
    dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  )
) %>%
  formatStyle(
    'Party',
    fontWeight = 'bold',
    backgroundColor = styleEqual(
      unique(tablepol$Party), c('deepskyblue','red', 'orange','green','yellow')
    )
  ) 
```
